version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "9008:9008"
    volumes:
      - .:/var/www/html
      - ./laravel.env:/var/www/html/.env:ro
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_KEY=${APP_KEY:-base64:...}
      - APP_DEBUG=${APP_DEBUG:-true}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE:-polatechdb}
      - DB_USERNAME=${DB_USERNAME:-admin}
      - DB_PASSWORD=${DB_PASSWORD:-admin123}
      - DB_SCHEMA=${DB_SCHEMA:-ticket}
    networks:
      - polatix

networks:
  polatix:
    external: true