FROM php:8.1-fpm

# Copy application code into the image
COPY . /var/www/html

# Set working directory to the application directory
WORKDIR /var/www/html

# Install PHP dependencies and required modules
RUN apt-get update && apt-get install -y \
    libzip-dev \
    zip \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip pdo pdo_mysql

# Set permissions for cache and log storage
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache
RUN chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache

# Set command to run when container starts
CMD php artisan serve --host=0.0.0.0 --port=8000
